/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipesRecipeNameRouteImport } from './routes/recipes/$recipeName'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRecipeNameRoute = RecipesRecipeNameRouteImport.update({
  id: '/recipes/$recipeName',
  path: '/recipes/$recipeName',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/recipes/$recipeName': typeof RecipesRecipeNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/recipes/$recipeName': typeof RecipesRecipeNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/recipes/$recipeName': typeof RecipesRecipeNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/recipes/$recipeName'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/recipes/$recipeName'
  id: '__root__' | '/' | '/recipes/$recipeName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RecipesRecipeNameRoute: typeof RecipesRecipeNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$recipeName': {
      id: '/recipes/$recipeName'
      path: '/recipes/$recipeName'
      fullPath: '/recipes/$recipeName'
      preLoaderRoute: typeof RecipesRecipeNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RecipesRecipeNameRoute: RecipesRecipeNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
